'use client';

import { useRouter } from 'next/navigation';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { FileText, ArrowLeft } from 'lucide-react';
import { useAuth } from '@/contexts/AuthContext';

export default function TermsOfServicePage() {
  const router = useRouter();
  const { user } = useAuth();

  return (
    <div className="min-h-screen bg-linear-to-br from-blue-50 via-purple-50 to-pink-50">
      {/* Header - Only show if logged in */}
      {user && <Header />}

      {/* Back Button */}
      <div className="max-w-4xl mx-auto px-4 pt-8">
        <button
          onClick={() => router.back()}
          className="flex items-center gap-2 text-purple-600 hover:text-purple-800 font-medium transition-colors"
        >
          <ArrowLeft className="w-5 h-5" />
          Back
        </button>
      </div>

      {/* Content */}
      <div className="max-w-4xl mx-auto px-4 py-12">
        <div className="bg-white rounded-3xl shadow-xl p-8 md:p-12">
          {/* Header */}
          <div className="text-center mb-8">
            <FileText className="w-16 h-16 text-purple-600 mx-auto mb-4" />
            <h1 className="text-4xl md:text-5xl font-bold text-purple-600 mb-2">
              Terms of Service
            </h1>
            <p className="text-xl text-gray-600">ImagiKids</p>
            <p className="text-sm text-gray-500 mt-2">
              Effective Date: January 10, 2026
            </p>
          </div>

          {/* Content */}
          <div className="space-y-8 text-gray-700">
            <p className="text-lg leading-relaxed">
              These Terms of Service (&quot;Terms&quot;) govern your use of the ImagiKids application.
            </p>

            <div className="bg-purple-50 border-l-4 border-purple-400 p-4 rounded">
              <p className="text-purple-800">
                <strong>By creating an account or using ImagiKids, you agree to these Terms.</strong>
              </p>
            </div>

            {/* Section 1 */}
            <section>
              <h2 className="text-2xl font-bold text-gray-800 mb-4">1. Acceptable Use</h2>
              <p className="mb-3">ImagiKids is intended for personal, family use, especially for bedtime stories for children.</p>
              <p className="mb-3">Parents or legal guardians are responsible for:</p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Supervising their child&apos;s use</li>
                <li>Managing story content</li>
                <li>Ensuring no sensitive personal information is entered</li>
              </ul>
            </section>

            {/* Section 2 */}
            <section>
              <h2 className="text-2xl font-bold text-gray-800 mb-4">2. Accounts</h2>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>An account is required to create and save stories.</li>
                <li>You must provide accurate information.</li>
                <li>You are responsible for keeping your login secure.</li>
              </ul>
            </section>

            {/* Section 3 */}
            <section>
              <h2 className="text-2xl font-bold text-gray-800 mb-4">3. Content Guidelines</h2>
              <p className="mb-3">To keep ImagiKids safe for children, users must not submit:</p>
              <ul className="list-disc list-inside space-y-2 ml-4 mb-4">
                <li>Violent, sexual, or frightening content</li>
                <li>Hate speech or harmful language</li>
                <li>Real personal information about children</li>
              </ul>
              <p className="italic">We reserve the right to remove content or suspend accounts that violate these rules.</p>
            </section>

            {/* Section 4 */}
            <section>
              <h2 className="text-2xl font-bold text-gray-800 mb-4">4. AI-Generated Content Disclaimer</h2>
              <p className="mb-3">All stories and images are generated by artificial intelligence.</p>
              <ul className="list-disc list-inside space-y-2 ml-4 mb-4">
                <li>Content is provided for entertainment and educational purposes only</li>
                <li>AI output may occasionally contain errors or unexpected results</li>
                <li>Parents should review content before sharing with children</li>
              </ul>
            </section>

            {/* Section 5 */}
            <section>
              <h2 className="text-2xl font-bold text-gray-800 mb-4">5. Intellectual Property</h2>
              <p className="mb-3"><strong>Users own</strong> the stories and images they create:</p>
              <ul className="list-disc list-inside space-y-2 ml-4 mb-4">
                <li>Users may save, download, and share content for personal use</li>
              </ul>
              <p className="mb-3"><strong>ImagiKids retains ownership of:</strong></p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>The app</li>
                <li>Branding</li>
                <li>Design</li>
                <li>Technology and software</li>
              </ul>
            </section>

            {/* Section 6 */}
            <section>
              <h2 className="text-2xl font-bold text-gray-800 mb-4">6. Payments & Pricing</h2>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Some features may require payment in the future to cover AI image generation costs.</li>
                <li>Pricing will be clearly displayed</li>
                <li>Any changes will be communicated in advance</li>
              </ul>
            </section>

            {/* Section 7 */}
            <section>
              <h2 className="text-2xl font-bold text-gray-800 mb-4">7. No Guarantees</h2>
              <p className="mb-3">ImagiKids is provided &ldquo;as is.&rdquo;</p>
              <p className="mb-3">We do our best to provide a reliable and safe experience, but we do not guarantee:</p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>Uninterrupted service</li>
                <li>Error-free AI output</li>
                <li>Availability of all features at all times</li>
              </ul>
            </section>

            {/* Section 8 */}
            <section>
              <h2 className="text-2xl font-bold text-gray-800 mb-4">8. Changes to the App or Terms</h2>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>We may update features or these Terms as the app evolves.</li>
                <li>Continued use of ImagiKids means acceptance of updated Terms.</li>
              </ul>
            </section>

            {/* Section 9 */}
            <section>
              <h2 className="text-2xl font-bold text-gray-800 mb-4">9. Termination</h2>
              <p className="mb-3">We may suspend or terminate access if:</p>
              <ul className="list-disc list-inside space-y-2 ml-4">
                <li>These Terms are violated</li>
                <li>Content guidelines are ignored</li>
                <li>The app is used in a harmful way</li>
              </ul>
            </section>

            {/* Section 10 */}
            <section>
              <h2 className="text-2xl font-bold text-gray-800 mb-4">10. Contact Information</h2>
              <p>
                📧 Email:{' '}
                <a
                  href="mailto:sherpa.sjs@gmail.com"
                  className="text-purple-600 hover:text-purple-800 font-semibold underline"
                >
                  sherpa.sjs@gmail.com
                </a>
              </p>
            </section>
          </div>
        </div>
      </div>

      {/* Footer */}
      <Footer />
    </div>
  );
}
